### ISSUE TITLE
Could Not find discord rpc 

### ISSUE THREAD

**Issue by ghost** [TheFrontier/Uplink#1]
I cloned the src code and tried to build the project.
I used the 1.7.10 one

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\hubbe\Desktop\test\build.gradle' line: 71

* What went wrong:
A problem occurred evaluating root project 'test'.
> Could not resolve all dependencies for configuration ':embed'.
   > Could not find com.github.MinnDevelopment:discord-rpc-release:-SNAPSHOT.
     Searched in the following locations:
         http://files.minecraftforge.net/maven/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         http://files.minecraftforge.net/maven/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.pom
         http://files.minecraftforge.net/maven/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.jar
         https://repo1.maven.org/maven2/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         https://repo1.maven.org/maven2/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.pom
         https://repo1.maven.org/maven2/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.jar
         https://libraries.minecraft.net/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         https://libraries.minecraft.net/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.pom
         https://libraries.minecraft.net/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.jar
         https://jcenter.bintray.com/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.pom
         https://jcenter.bintray.com/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.jar
         https://jitpack.io/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         https://jitpack.io/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--v3.3.0-gdb2ee1d-1.pom
         https://jitpack.io/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--v3.3.0-gdb2ee1d-1.jar
     Required by:
         project : > com.github.MinnDevelopment:Java-DiscordRPC:v1.3.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.086 secs

**Comment by JoshOOOOWAH** [comment]
You can use my PR #2
